### ISSUE TITLE
how to start

### ISSUE THREAD

**Issue by Heisenbilin** [duxianwei520/express#1]
运行npm start后没有跳出东西来，浏览器写localhost：3000也没有东西，怎么在浏览器端进行输入呢

**Comment by duxianwei520** [comment]
@Heisenbilin 这个npm start只是启动了一个nodejs的服务，这个服务里面有接口的，比如登录，注册的接口，你用post请求对应的login跟register接口就知道了，看看代码，然后这个还需要你创建一个mysql的数据库，具体的你可以看看代码，没几行的说
